package dinodungeons.editor.map.change;

public enum MapChangeType {
	NONE,
	BASE_LAYER,
	COLLECTABLE_ITEM,
	SWITCH_PLACEMENT,
	DOOR_PLACEMENT,
	EXIT_PLACEMENT,
	DESTRUCTIBLE_PLACEMENT,
	SPIKE_PLACEMENT,
	IMMOVABLE_PLACEMENT;
}
