package dinodungeons.editor;

public enum EditorState {
	INSPECTOR,
	PLACE_BASELAYER,
	CHANGE_TILESET,
	PLACE_EXITS,
	PLACE_ITEMS,
	PLACE_DUNGEON_ITEMS,
	PLACE_SPIKES,
	ENTER_TEXT,
	PLACE_DESTRUCTABLES,
	PLACE_ENEMIES,
	PLACE_BLOCKS,
	PLACE_DOORS
}
